#!/usr/bin/env bash

export PATH="/root/miniconda3/bin:$PATH"

# Sets up so session can use conda environments.
source /root/miniconda3/etc/profile.d/conda.sh

# Defines the variable exercise_name with name of exercise.
source /autograder/source/exercise_name.sh

# Check submission count
conda activate grader
python /autograder/source/limit_num_submissions.py

# Exit if not return code 0 from above
if [ $? != 0 ];
then
    exit 0
fi

# Actually Grade
cp /autograder/submission/${exercise_name}.ipynb /autograder/source/${exercise_name}.ipynb
cd /autograder/source/
jupyter nbconvert --execute ${exercise_name}.ipynb --to script
mv ${exercise_name}.py submission_script.py
pytest
cp /autograder/source/results.json /autograder/results/results.json
